name: Deploy a simple web application using github actions
on:
 push:
    branches:
      - main
jobs:
  build-container:
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        uses: actions/checkout@v2

      - name: build docker image
        run: |
             docker build -t ramkyalla/web-app:v1 .  
      - name: fetch the list of docker images
        run: |
             docker images -a   

      - name: login to docker hub
        run: docker login -u ${{ vars.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
          
             
      - name: push the docker image to docker hub
        run: |
             docker push ramkyalla/web-app:v1

  deploy-application-to-kubernetes:
    runs-on: windows
    steps:
      - name: check the connectivity
        run: kubectl cluster-info
        env:
          KUBECONFIG: C:\Users\yrkre\.kube\config

      - name: list the pods
        run: kubectl get pods -A
        env:
          KUBECONFIG: C:\Users\yrkre\.kube\config

      - name: deploy application via yaml file
        run: kubectl apply -f C:\Users\santo\Documents\projects\devops_project_1\deploy.yml
        env:
          KUBECONFIG: C:\Users\yrkre\.kube\config

      - name: deploy service via yaml file
        run: kubectl apply -f C:\Users\santo\Documents\projects\devops_project_1\service.yml
        env:
          KUBECONFIG: C:\Users\yrkre\.kube\config

          
      - name: list the pods
        run: kubectl get pods -A
        env:
          KUBECONFIG: C:\Users\yrkre\.kube\config 
       
